# Description: Service for the Nginx deployment
# Service is used to expose the deployment outside the cluster

apiVersion: v1
kind: Service
metadata:
  name: kuber-service-nginx
spec:
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
