# Description: livelessProbe with exec command
# LivenessProbe is used to know if the container is alive or not. If the container is not alive, then the container will be restarted.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-deployment
  template:
    metadata:
      labels:
        app: ubuntu-deployment
    spec:
      containers:
        - name: ubuntu-deployment
          image: ubuntu:latest
          args:
            - /bin/sh
            - -c
            - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5 # Default value is 0. Minimum value is 0. It is the time to wait before performing the first probe.
            periodSeconds: 5 # Default value is 10. Minimum value is 1. It is the time to wait between probes.
            timeoutSeconds: 1 # Default value is 1. Minimum value is 1. It is the time to wait for the probe to return a result.
            successThreshold: 1 # Default value is 1. Minimum value is 1. It is the number of consecutive successful probes for the container to be considered healthy.
            failureThreshold: 3 # Default value is 3. Minimum value is 1. It is the number of consecutive failed probes for the container to be considered unhealthy.
