# Description: Service with NodePort type
# NodePort service type is used to expose the service on each node's IP at a static port.
# sessionAffinity is set to ClientIP to ensure that the requests from the same client are always routed to the same pod.

apiVersion: v1
kind: Service
metadata:
  name: kuber-service-node-port
spec:
  # sessionAffinity: ClientIP
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
  type: NodePort
