# Description: Service with LoadBalancer type
# LoadBalancer service type is used to expose the service outside the cluster using the cloud provider's load balancer.

apiVersion: v1
kind: Service
metadata:
  name: kuber-service-load-balancer
spec:
  externalTrafficPolicy: Local
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
