apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-args
  labels:
    app: kuber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuber-server-args
  template:
    metadata:
      labels:
        app: kuber-server-args
    spec:
      containers:
        - name: kuber-app-args
          image: k8s-tips:latest
          command: ["python3", "-u", "server-default.py"] # set the default command
          args: ["1", "3"] # set the default arguments
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-service-args
spec:
  selector:
    app: kuber-server-args
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001
  type: NodePort
